name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt install libpulse-dev
    - name: Formatting check
      run: |
        rustup toolchain add nightly
        rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
        cargo +nightly fmt -- --check
    - name: Clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
